### ISSUE TITLE
Namespace conflict with autogenerated code.

### ISSUE THREAD

**Issue by knstntn** [microsoft/Omex#101]
## Context
I made new namespace `Microsoft.Omex.Metrics.ApiClient` and used this namespace for ApiClient generated using nswag https://github.com/RicoSuter/NSwag

Result is shown on this picture
![image](https://user-images.githubusercontent.com/5101272/63170963-711af280-c032-11e9-8169-ae29bd7bfac1.png)

## Current Behavior
Compilation failed because `System` resolved to `Microsoft.Omex.System`

## Expected Behavior
Compilation is fine.

## Possible Solution
I think proper solution would be to update nswag to generate code using `global::` alias for `System`, and I plan to send report to them

But you cannot change all generators in the world, so I think it is appropriate to rename Microsoft.Omex.System to avoid namespace conflicts.

## Environment
NSwag version 11.20.1

**Comment by knstntn** [comment]
Added PR for NSwag https://github.com/RicoSuter/NSwag/pull/2356

**Comment by AndreyTretyak** [comment]
Omex.System deprecated and we are not using Omex.System namespace anymore, thank you for pointing this out.
