### ISSUE TITLE
Add more helper methods for settings result on Activity

### ISSUE THREAD

**Issue by AndreyTretyak** [microsoft/Omex#265]
Currently, activity has extension methods 
https://github.com/microsoft/Omex/blob/a6ac88ec960000bc14562fa2215a7bbb8b486140/src/Extensions/Abstractions/Activities/ActivityExtensions.cs#L60

It looks like they are using a lot, so it would be nice to have additions methods to simplify interactions, for example:
```CSharp
public static Activity MarkAsSuccess(this Activity activity) { ... }
public static Activity MarkAsSystemError(this Activity activity) { ... }
public static Activity MarkAsExpectedError(this Activity activity) { ... }
```
They would be calling `SetResult` inside, also some simple unit tests needed for it.

**Comment by MatusTomko** [comment]
i want to do this isssue

**Comment by MatusTomko** [comment]
@AndreyTretyak how can i push my changes there?

**Comment by AndreyTretyak** [comment]
@MatusTomko you need to 
1. fork a repository
![image](https://user-images.githubusercontent.com/2550113/97894799-d851bf00-1d2a-11eb-9aaa-3228103c73d8.png)
2. Then you would be able to push your local branch to the forked repository (if you already have a branch in your local copy you can just replace the URL of the remote or add a second remote to push). https://docs.github.com/en/free-pro-team@latest/github/using-git/changing-a-remotes-url
3. Then you can use GitHub UI to create a pull request from a branch in your fork into the master of this repository. https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

Please let me know if you would have problems with any of the steps.

**Comment by MatusTomko** [comment]
@AndreyTretyak I have a problem with Perform CodeQL Analysis, do you know what is problem?
![image](https://user-images.githubusercontent.com/72621093/97917860-6fcc0780-1d55-11eb-9e98-a043c1168483.png)

**Comment by AndreyTretyak** [comment]
@MatusTomko I think it was intermittent (that build stage not required), I've restarted pipelines and it looks successful now.
