### ISSUE TITLE
Process components are not managed correctly

### ISSUE THREAD

**Issue by K-Cully** [microsoft/Omex#453]
In some logging classes Process.GetCurrentProcess is used incorrectly.
See https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1837 regarding the issues.

For initialization logger, the code should be updated to Environment.ProcessId (https://docs.microsoft.com/en-us/dotnet/api/system.environment.processid?view=net-6.0).
For OmexLogEventSender, the process should be created in a using scope to ensure it is disposed correctly.

See https://github.com/microsoft/Omex/search?q=GetCurrentProcess

**Comment by artempushkin** [comment]
Good catch.
