### ISSUE TITLE
Gating configuration not taken into account

### ISSUE THREAD

**Issue by dakanev-msft** [microsoft/Omex#46]
Specified resource file names are ignored, and the default names OmexTip.xml and OmexGates.xml are always used instead. This manifests as gates being loaded as disabled (due to a data set load error) and the gating is effectively not working.

The workaround for this issue is to rename the resource files to OmexTip.xml and OmexGates.xml.

**Comment by dakanev-msft** [comment]
This is worked on as part of https://github.com/microsoft/Omex/pull/66

**Comment by dakanev-msft** [comment]
Closed in commit 66a70c78206cd094717f8fe19fff214da7cac563

**Comment by dakanev-msft** [comment]
The fix caused unit tests in other components to fail. The corresponding commit will be reverted.

**Comment by K-Cully** [comment]
Gating is no longer in this repo, or supported.
