### ISSUE TITLE
Transfer TimedScope logging class

### ISSUE THREAD

**Issue by mastac-msft** [microsoft/Omex#81]
The TimedScope unit test class is missing two tests at the moment: FailedTimedScope_Logs_in79_and_in7b and SuccessfulTimedScope_Logs_in79_and_in7a.
In order to complete the transfer the implementation of ITimedScopeLogger is required (UlsTimedScopeLogger class).

**Comment by AndreyTretyak** [comment]
We are changing TimedScopes reporting mechanism so those UT won't be needed
