### ISSUE TITLE
Add Correlation to ULSLogging

### ISSUE THREAD

**Issue by mastac-msft** [microsoft/Omex#87]
- As the Correlation logic was added to LogEventArgs (parameters Correlation and ShouldLogDirectly), it needs to be added to ULSLogging. For this moment the Correlation is set to null, and ShouldLogDirectly to false.
- The details parameter of LogEventArgs is currently set to string.Empty, should be replaced with Logs.GetGateIds() method, which require GateContext initialization.

**Comment by AndreyTretyak** [comment]
Correlation now based on System.Diagnostics.Activity, so there is no need of adding those fields to ULSLogging
